[windows]
10.0.1.132 zabbix_source_ip=172.16.10.54 zabbix_server_ip=10.0.1.120

[windows:vars]
ansible_user=ox
ansible_password=Adetola123
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
#ansible_winrm_scheme=https
ansible_port=5985
#ansible_shell_type=powershell
ansible_system=Windows
ansible_python_interpreter=auto_silent
