# docker-compose.yml
version: '3.8'

services:
  loki:
    image: grafana/loki:3.4
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
# THIS SHOULD BE THE SAME NETWOR AS GRAFANA FOR EASE.
    networks:
      management_net:
        ipv4_address: 172.28.30.17
networks:
  management_net:
    external: true
