[webservers]
192.168.101.3  # Replace with your server IP

[webservers:vars]
# Variables for all webservers
ansible_user = vagrant
#ansible_ssh_password="@Loveisinme85"
ansible_ssh_private_key_file = ./key

# Assign roles to this group
#ansible_playbook_roles = ansible-role-docker, ansible-role-mysql
