services:
  traefik:
    container_name: traefik-4
    image: traefik:3.4
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      traefik:
    ports:
      - "80:80"
#      - "81:81"
      - "443:443"
      - "444:444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Enable if not using Socket Proxy
      - ${HOME_DIRECTORY}/config/acme.json:/acme.json # Certs File 
      - ${HOME_DIRECTORY}/logs/traefik.log:/logs # Traefik logs
      - ${HOME_DIRECTORY}/config/traefik.yml:/traefik.yml
      - ${HOME_DIRECTORY}/dynamic:/etc/traefik/dynamic
    environment:
      - TZ=$TZ
      - CF_API_EMAIL=$CF_API_EMAIL
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
      - DOMAIN_NAME=$DOMAIN_NAME
      - HOME_DIRECTORY=$HOME_DIRECTORY
    #secrets:
     # - cf_dns_api_token
    #  - basic_auth_credentials
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=websecure"
      - "traefik.http.routers.traefik-rtr.rule=Host(`board.oxtech.me`)"
      # Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      # Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=redirect@file"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare"
#,authentik@file"

networks:
  traefik:
    external: true
