services:
  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana_enterprise
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SMTP_HOST=${GF_SMTP_HOST}  
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=Grafana
      - GF_SMTP_SKIP_VERIFY=${GF_SMTP_SKIP_VERIFY}

    user: "${UID}:${GID}"
    volumes:
      - "${DOCKERDIR}/config:/var/lib/grafana"
      - "${DOCKERDIR}/grafana.ini:/etc/grafana/grafana.ini"
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`graf.${DOMAINNAME}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.grafana.middlewares=redirect@file"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls.certresolver=dns-cloudflare"
networks:
  traefik:
    external: true
