services:
  grafana:
    image: grafana/grafana:11.6.1
    container_name: grafana_enterprise
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    user: "${UID}:${GID}"
    volumes:
      - "${DOCKERDIR}/config:/var/lib/grafana"
    restart: unless-stopped
    networks:
      - grafana
    ports:
     - '3005:3000'
networks:
  grafana:
    external: true
