limit_req_zone $binary_remote_addr zone=req_limit_per_ip:10m rate=5r/s;
server {
    listen 80;
    server_name xxxxx;
    if ($host !~* ^(xxxxx|localhost|127.0.0.1)$ ) {
        return 444;
    }

    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;
    
    keepalive_timeout 30;
    keepalive_requests 100;

    client_max_body_size 200M;
    server_tokens off;

    more_set_headers 'Server: Unknown entity. Try again.';

    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";
    add_header Content-Security-Policy "frame-ancestors 'none'" always;
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "no-referrer";
    add_header Permissions-Policy "geolocation=(), microphone=()";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    location ~ /\. {
        deny all;
        limit_req zone=req_limit_per_ip burst=20 nodelay;
        access_log off;
        log_not_found off;

    }

    # Certbot challenge directory
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }


    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ \.php$ {
        try_files $uri /index.php?$query_string;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
            limit_req zone=req_limit_per_ip burst=20 nodelay;
        fastcgi_index index.php;
        include fastcgi_params;
	fastcgi_read_timeout 300;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

}

server {
    listen 80;
    server_name www.xxxxx.in;
    client_max_body_size 200M;    
    # Certbot challenges 
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }
    
    # Redirect HTTP www to HTTPS www
    return 301 https://xxxxx.in$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443;
    http2 on;
    server_name www.xxxxx.in;
    client_max_body_size 200M;
    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/xxxxx.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxxxxx.in/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/xxxxx.in/chain.pem;
    return 301 https://xxxxx.in$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name xxxxxx.in;

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/xxxxx.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxxxx.in/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/xxxx.in/chain.pem;

    client_max_body_size 100M;
    # Root and index
    root /var/www/public;
    index index.php index.html index.htm;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Certbot renewal challenges
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Main handling
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP handling
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
	fastcgi_read_timeout 300;        
    }


    # Deny access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}